language: node_js
node_js:
  - "node"
branches:
  only:
    - master
install:
  - npm install -g rollup
  - npm install
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: $npm_email
  api_key:
    secure: $npm_token
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    recipients:
    - $npm_email
    on_success: change
    on_failure: always
