language: node_js
node_js:
  - "node"
branches:
  only:
    - master
install:
  - npm install -g rollup
  - npm install cross-env
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  email: $npm_email
  api_key:
    secure: $npm_token
  on:
    repo: ranpa/capitalize-pt-br
